apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: om-secrets
spec:
  name: om-secrets
  keysMap:
    credentials_cfg:
      path: secrets/data/infra-common/om
      key: mindspore_credentials.cfg
    projects_json:
      path: secrets/data/infra-common/om
      key: mindspore_projects.json
